services:
  mysql:
    image: mysql:8.0
    container_name: mysql_perf_test
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
